### ISSUE TITLE
为什么不用Oneindex来分享资料呢？

### ISSUE THREAD

**Issue by Snowflake-Pink** [jybicu/whk#4]
RT，这个很方便啊，加一个空间就可以了，项目在github上有，空间50～60RMB一年，Onedrive 5T云盘账号5RMB，下载使用迅雷3MB/s起步，还可以在线看，根本不用麻烦大家用百度云会员。个人建议，希望可以认真考虑一下～

**Comment by memset0** [comment]
可以的，这些都不是问题，关键在于没有资源和规划。

**Comment by memset0** [comment]
等到内容一步步完善了这些相关的功能肯定会跟上的。

**Comment by Snowflake-Pink** [comment]
好的

**Comment by YoungZM339** [comment]
也许可以看看我的Oneindex?内含100GB+文化课资料[https://pan.youngzm.com/Video/](https://pan.youngzm.com/Video/)
